// Generated by CoffeeScript 1.4.0
/*
Module dependencies.
*/

var app, express, http, path, rootDir, routes, user;

express = require("express");

routes = require("./routes");

user = require("./routes/user");

http = require("http");

path = require("path");

app = express();

rootDir = __dirname.substring(0, __dirname.lastIndexOf("/"));

app.configure(function() {
  app.set("port", process.env.PORT || 3000);
  app.set("views", rootDir + "/views");
  app.set("view engine", "jade");
  app.use(express.favicon());
  app.use(express.logger("dev"));
  app.use(express.bodyParser());
  app.use(express.methodOverride());
  app.use(app.router);
  app.use(require("stylus").middleware(rootDir + "/public"));
  return app.use(express["static"](path.join(rootDir, "public")));
});

app.configure("development", function() {
  return app.use(express.errorHandler());
});

app.get("/", routes.index);

app.get("/users", user.list);

http.createServer(app).listen(app.get("port"), function() {
  return console.log("Express server listening on port " + app.get("port"));
});
