// Generated by CoffeeScript 1.4.0
var Post, model;

model = require("../model");

Post = model.Post;

exports.index = function(req, res) {
  return Post.find({}, function(err, items) {
    return res.render("index", {
      title: "Entry List",
      items: items
    });
  });
};

exports.form = function(req, res) {
  return res.render("form", {
    title: "New Entry"
  });
};

exports.create = function(req, res) {
  var newPost;
  newPost = new Post(req.body);
  return newPost.save(function(err) {
    if (err) {
      console.log(err);
      return res.redirect("back");
    } else {
      return res.redirect("/");
    }
  });
};
